name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
softdepend: [Vault, UILib, Multiverse-Core, MultiWorld]
author: Narwhal
description: Teleport to any biome instantly.
commands:
  bftp:
    description: Go to a biome.
    usage: "/<command> <biome> [keyword] [player]"
    aliases: bfind
  bcachebuild:
    description: "Build a cache of biome locations. This can cause severe lag during the build process. Necessary for each world you want to use biome search functions in."
    usage: "/<command> <world> ([spawn] | [<x> <z>])"
    permission: "biomefinder.command.bcachebuild"
  biomereload:
    description: Reload the config.
    usage: /<command>
  bsearch:
    description: List nearby biomes.
    usage: /<command>
permissions:
  biomefinder.tp:
    description: Teleport to a biome using commands.
    default: op
    children:
      biomefinder.find: true
  biomefinder.tp.other:
    description: Teleport another player to a biome using commands. If you grant this you should grant biomefinder.tp as well.
    default: op
  biomefinder.find:
    description: This node may be removed at some point. Use biomefinder.tp instead. Teleport to a biome using commands.
    default: false
  biomefinder.create:
    description: "Create a [BiomeTP] sign."
    default: op
  biomefinder.create.cost:
    description: "Create a [BiomeTP] sign that charges players for using it."
    default: op
  biomefinder.reload:
    description: Reload the config.
    default: op
  biomefinder.bsearch:
    description: List nearby biomes.
    default: op
  biomefinder.command.bcachebuild:
    description: Build biome caches.
    default: op
